config/routes.rb
# frozen_string_literal: true

# routes.rb style guidance:
#
# - Root at the top
# - Unscoped routes next; group them logically
# - Throw everything else in a scope, alphabetically ordered.
# - Within a scope, unscoped routes go _after_ everything else.
# - Unscoped mounts at the bottom.
#
# RubyMine hint: Within the draw block, Ctrl-Shift-Minus followed by Ctrl-= (or cmd, whatever system you're on)
# will collapse everything and then expand the top level again so you just see unscoped routes plus scopes. Makes
# it much easier to see where everything is.
Rails.application.routes.draw do
  # Needs both with and without :as, ref Charcoal-SE/metasmoke#247
  root               to: 'dashboard#new_dash',  as: :dashboard
  root               to: 'dashboard#new_dash'

  resources :dumps

  get    'sites/dash',            to: 'dashboard#site_dash',        as: :site_dash

  get    'search',                to: 'search#index'
  get    'search_fast',           to: 'search#index_fast'
  get    'reasons',               to: 'dashboard#index',            as: :reasons
  get    'flagging',              to: 'flag_settings#dashboard',    as: :flagging

  get    'query-times',           to: 'dashboard#query_times',      as: :query_times
  post   'query-times/reset',     to: 'dashboard#reset_query_time', as: :reset_query_time

  post   'statistics.json',       to: 'statistics#create'
  post   'feedbacks.json',        to: 'feedbacks#create'
  post   'posts.json',            to: 'posts#create'
  post   'deletion_logs.json',    to: 'deletion_logs#create'
  post   'status-update.json',    to: 'status#status_update'

  delete 'feedback/:id/delete',   to: 'feedbacks#delete',           as: :delete_feedback

  devise_for :users, controllers: { sessions: 'custom_sessions', registrations: 'custom_registrations' }
  devise_scope :user do
    get  'users/2fa/login', to: 'custom_sessions#verify_2fa'
    post 'users/2fa/login', to: 'custom_sessions#verify_code'
  end

  scope 'abuse' do
    scope 'contacts' do
      root               to: 'abuse_contacts#index',   as: :abuse_contacts
      post   'new',      to: 'abuse_contacts#create',  as: :create_abuse_contact
      get    ':id',      to: 'abuse_contacts#show',    as: :abuse_contact
      get    ':id/edit', to: 'abuse_contacts#edit',    as: :edit_abuse_contact
      patch  ':id/edit', to: 'abuse_contacts#update',  as: :update_abuse_contact
      delete ':id',      to: 'abuse_contacts#destroy', as: :destroy_abuse_contact
    end

    scope 'statuses' do
      root               to: 'abuse_report_statuses#index',   as: :abuse_statuses
      post   'new',      to: 'abuse_report_statuses#create',  as: :create_abuse_status
      get    ':id',      to: 'abuse_report_statuses#show',    as: :abuse_status
      get    ':id/edit', to: 'abuse_report_statuses#edit',    as: :edit_abuse_status
      patch  ':id/edit', to: 'abuse_report_statuses#update',  as: :update_abuse_status
      delete ':id',      to: 'abuse_report_statuses#destroy', as: :destroy_abuse_status
    end

    scope 'reports' do
      root                   to: 'abuse_reports#index',         as: :abuse_reports
      get    'new',          to: 'abuse_reports#new',           as: :new_abuse_report
      post   'new',          to: 'abuse_reports#create',        as: :create_abuse_report
      get    'shared/:uuid', to: 'abuse_reports#public_link',   as: :shared_abuse_report
      get    ':id',          to: 'abuse_reports#show',          as: :abuse_report
      patch  ':id/edit',     to: 'abuse_reports#update',        as: :update_abuse_report
      post   ':id/status',   to: 'abuse_reports#update_status', as: :update_abuse_report_status
      delete ':id',          to: 'abuse_reports#destroy',       as: :destroy_abuse_report
    end

    scope 'comments' do
      post   'new',        to: 'abuse_comments#create',  as: :create_abuse_comment
      get    ':id',        to: 'abuse_comments#text',    as: :comment_abuse_text
      post   ':id/edit',   to: 'abuse_comments#update',  as: :edit_abuse_comment
      delete ':id/delete', to: 'abuse_comments#destroy', as: :delete_abuse_comment
    end
  end

  scope 'admin' do
    scope 'settings' do
      root                 to: 'site_settings#index',   as: :site_settings
      post   ':name',      to: 'site_settings#update',  as: :update_site_setting
      delete ':id/delete', to: 'site_settings#destroy', as: :destroy_site_setting
    end

    root                           to: 'admin#index'
    get    'invalidated',          to: 'admin#recently_invalidated'
    get    'user_feedback',        to: 'admin#user_feedback',               as: :admin_user_feedback
    get    'api_feedback',         to: 'admin#api_feedback'
    get    'flagged',              to: 'admin#flagged'
    post   'clear_flag',           to: 'admin#clear_flag'
    get    'users',                to: 'admin#users',                       as: :user_data
    get    'permissions',          to: 'admin#permissions',                 as: :admin_permissions
    put    'permissions/update',   to: 'admin#update_permissions'
    delete 'permissions/:user_id', to: 'admin#destroy_user'

    get    'invalidate_tokens',    to: 'authentication#invalidate_tokens'
    post   'invalidate_tokens',    to: 'authentication#send_invalidations'

    get    'new_key',              to: 'api_keys#new',                      as: :admin_new_key
    post   'new_key',              to: 'api_keys#create'
    get    'keys',                 to: 'api_keys#index'
    get    'keys/mine',            to: 'api_keys#mine'
    get    'edit_key/:id',         to: 'api_keys#edit'
    patch  'edit_key/:id',         to: 'api_keys#update'
    get    'owner_edit/:id',       to: 'api_keys#owner_edit'
    patch  'owner_edit/:id',       to: 'api_keys#owner_update'
    delete 'revoke_write',         to: 'api_keys#revoke_write_tokens'
    delete 'owner_revoke',         to: 'api_keys#owner_revoke'
    post   'keys/:id/trust',       to: 'api_keys#update_trust'
  end

  scope 'announcements' do
    root               to: 'announcements#index',  as: :announcements
    post ':id/expire', to: 'announcements#expire', as: :announcements_expire
    get  'new',        to: 'announcements#new'
    post 'new',        to: 'announcements#create'
    post 'enable',     to: 'users#set_announcement_emails'
  end

  scope 'api' do
    root                            to: 'api#api_docs',              as: :api_docs
    get  'filters',                 to: 'api#filter_generator'
    post 'filters',                 to: 'api#calculate_filter'

    get  'filter_fields',           to: 'api#filter_fields'
    get  'stats/last_week',         to: 'api#spam_last_week'
    get  'stats/detailed_ttd',      to: 'api#detailed_ttd'
    get  'smoke_detectors/status',  to: 'api#current_status'
    get  'smoke_detectors',         to: 'api#smoke_detectors'
    get  'posts/urls',              to: 'api#posts_by_url'
    post 'posts/urls',              to: 'api#posts_by_url'
    get  'posts/feedback',          to: 'api#posts_by_feedback'
    get  'posts/undeleted',         to: 'api#undeleted_posts'
    get  'posts/site',              to: 'api#posts_by_site'
    get  'posts/between',           to: 'api#posts_by_daterange'
    get  'posts/search',            to: 'api#search_posts'
    get  'posts/:ids',              to: 'api#posts'
    get  'post/:id/feedback',       to: 'api#post_feedback'
    get  'post/:id/reasons',        to: 'api#post_reasons'
    get  'post/:id/valid_feedback', to: 'api#post_valid_feedback'
    get  'reasons',                 to: 'api#all_reasons'
    get  'reasons/:ids',            to: 'api#reasons'
    get  'reason/:id/posts',        to: 'api#reason_posts'
    get  'blacklist',               to: 'api#blacklisted_websites'
    get  'users',                   to: 'api#users',                 as: :api_users
    get  'users/code_privileged',   to: 'api#users_with_code_privs'
    get  'post/:id/domains',        to: 'api#post_domains',          as: :api_post_domains
    get  'domains/:id/tags',        to: 'api#domain_tags',           as: :api_domain_tags

    post 'w/post/:id/feedback',     to: 'api#create_feedback'
    post 'w/post/report',           to: 'api#report_post'
    post 'w/post/:id/spam_flag',    to: 'api#spam_flag'
    post 'w/post/:id/deleted',      to: 'api#post_deleted'
    post 'w/domains/:id/add_tag',   to: 'api#add_domain_tag',        as: :api_add_domain_tag

    post 'graphql',                 to: 'graphql#execute',           as: :graphql
    get 'graphql',                  to: 'graphql#query',             as: :query_graphql
  end
  mount GraphiQL::Rails::Engine,  at: '/api/graphiql',                 graphql_path: '/api/graphql', query_params: true

  scope 'authentication' do
    get 'status',                to: 'authentication#status', as: :authentication_status
    get 'redirect_target',       to: 'authentication#redirect_target'
    get 'login_redirect_target', to: 'authentication#login_redirect_target'
  end

  scope 'channels' do
    post 'receive_email', to: 'channels#receive_email',     as: :channels_receive_email
    get  'email',         to: 'channels#get_email_address', as: :channels_email
    get  'link',          to: 'channels#show_link',         as: :channels_link
  end

  scope 'comments' do
    post 'new',          to: 'post_comments#create',  as: :create_comment
    get  ':id',          to: 'post_comments#text',    as: :comment_text
    post ':id/edit',     to: 'post_comments#update',  as: :edit_comment
    delete ':id/delete', to: 'post_comments#destroy', as: :delete_comment
  end

  scope 'data' do
    authenticate(:user, ->(user) { user.has_role?(:core) }) do
      mount Blazer::Engine, at: 'sql'
    end
  end

  scope 'dev' do
    post 'update_sites',     to: 'developer#update_sites',          as: :dev_update_sites
    get  'prod_log',         to: 'developer#production_log',        as: :dev_prod_log

app/controllers/search_controller.rb
# frozen_string_literal: true

class SearchController < ApplicationController
  def index
    # This might be ugly, but it's better than the alternative.
    #
    # And it's kinda clever.

    title, title_operation,
    body, body_operation,
    why, why_operation,
    username, username_operation = %i[title body why username].map do |s|
      SearchHelper.parse_search_params(params, s, current_user)
    end.flatten

    if [title_operation, body_operation, why_operation, username_operation].any?(&:!)
      render json: { error: 'Unauthenticated users cannot use regex search' }, status: 403
      return
    end

    user_reputation = params[:user_reputation].to_i || 0

    case params[:feedback]
    when /true/
      feedback = :is_tp
    when /false/
      feedback = :is_fp
    when /NAA/
      feedback = :is_naa
    end

    @results = if params[:reason].present?
                 Reason.find(params[:reason]).posts.includes_for_post_row
               else
                 Post.all.includes_for_post_row
               end

    per_page = user_signed_in? && params[:per_page].present? ? [params[:per_page].to_i, 10_000].min : 100

    search_string = []
    search_params = {}
    [[:username, username, username_operation], [:title, title, title_operation],
     [:why, why, why_operation]].each do |si|
      if si[1].present? && si[1] != '%%'
        search_string << "IFNULL(`posts`.`#{si[0]}`, '') #{si[2]} :#{si[0]}"
        search_params[si[0]] = si[1]
      end
    end

    if body.present?
      if ['LIKE', 'NOT LIKE'].include?(body_operation) && params[:body_is_like] != '1'
        # If the operation would be LIKE, hijack it and use our fulltext index for a search instead.
        # UNLESS... params[:body_is_like] is set, in which case the user has explicitly specified a LIKE query.
        @results = @results.match_search(body, with_search_score: false, posts: :body)
      else
        if params[:body_is_like] == '1' && !user_signed_in?
          flash[:warning] = 'Unregistered users cannot use LIKE searches on the body field. Please sign in.'
          redirect_to(search_path) && return
        end
        # Otherwise, it's REGEX or NOT REGEX, which fulltext won't do - fall back on search_string and params
        search_string << "IFNULL(`posts`.`body`, '') #{body_operation} :body"
        search_params[:body] = body.present? ? body : '%%'
      end
    end

    @results = @results.where(search_string.join(params[:or_search].present? ? ' OR ' : ' AND '), **search_params)
    @results = @results.includes(:reasons).includes(:feedbacks) if params[:option].nil?

    if params[:has_no_feedback] == '1'
      @results = @results.joins('LEFT JOIN feedbacks fbcounter ON fbcounter.post_id = posts.id').where('fbcounter.id is null')
    end

    if feedback.present?
      @results = @results.where(feedback => true)
    elsif params[:feedback] == 'conflicted'
      @results = @results.where(is_tp: true, is_fp: true)
    end

    @results = case params[:user_rep_direction]
               when '>='
                 @results.where('IFNULL(user_reputation, 0) >= :rep', rep: user_reputation) if user_reputation.positive?
               when '=='
                 @results.where('IFNULL(user_reputation, 0) = :rep', rep: user_reputation)
               when '<='
                 @results.where('IFNULL(user_reputation, 0) <= :rep', rep: user_reputation)
               else
                 @results
               end

    @results = @results.where(site_id: params[:site]) if params[:site].present?

    @results = @results.where('revision_count > 1') if params[:edited].present?

    @results = @results.includes(feedbacks: [:user])

    case params[:autoflagged].try(:downcase)
    when 'yes'
      @results = @results.autoflagged
    when 'no'
      @results = @results.not_autoflagged
    end

    post_type = case params[:post_type].try(:downcase).try(:[], 0)
                when 'q'
                  'questions'
                when 'a'
                  'a'
                end

    if post_type.present?
      unmatched = @results.where.not("link LIKE '%/questions/%' OR link LIKE '%/a/%'")
      @results =  if params[:post_type_include_unmatched]
                    @results.where('link like ?', "%/#{post_type}/%").or(unmatched)
                  else
                    @results.where('link like ?', "%/#{post_type}/%")
                  end
    end

    respond_to do |format|
      format.html do
        @counts_by_accuracy_group = @results.group(:is_tp, :is_fp, :is_naa).count
        @counts_by_feedback = %i[is_tp is_fp is_naa].each_with_index.map do |symbol, i|
          [symbol, @counts_by_accuracy_group.select { |k, _v| k[i] }.values.sum]
        end.to_h
        @total_count = @counts_by_accuracy_group.values.sum

        @results = case params[:feedback_filter]
                   when 'tp'
                     @results.where(is_tp: true)
                             .paginate(page: params[:page], per_page: per_page,
                                       total_entries: @counts_by_feedback[:is_tp])
                   when 'fp'
                     @results.where(is_fp: true)
                             .paginate(page: params[:page], per_page: per_page,
                                       total_entries: @counts_by_feedback[:is_fp])
                   when 'naa'
                     @results.where(is_naa: true)
                             .paginate(page: params[:page], per_page: per_page,
                                       total_entries: @counts_by_feedback[:is_naa])
                   else
                     @results.paginate(page: params[:page], per_page: per_page,
                                       total_entries: @total_count)
                   end.order(Arel.sql('`posts`.`created_at` DESC'))

        render :search
      end
      format.json do
        render json: @results
      end
      format.rss { render :search, layout: false }
      format.xml { render 'search.rss', layout: false }
    end
  end
end

app/helpers/search_helper.rb
# frozen_string_literal: true

module SearchHelper
  def self.parse_search_params(params, symbol, user)
    input = params[symbol] || ''

    if params[is_regex?(symbol)]
      operation = if !user.nil? && user.can_use_regex_search?
                    params[is_inverse_regex?(symbol)] ? 'NOT REGEXP' : 'REGEXP'
                  else
                    false
                  end
    else
      operation = 'LIKE'
      input = "%#{ActiveRecord::Base.sanitize_sql_like(input)}%" unless input.nil? || input.empty?
    end

    [input, operation]
  end

  def self.is_regex?(symbol) # rubocop:disable Naming/PredicateName
    "#{symbol}_is_regex".to_sym
  end

  def self.is_inverse_regex?(symbol) # rubocop:disable Naming/PredicateName
    "#{symbol}_is_inverse_regex".to_sym
  end
end

app/views/search/new_search.html.erb
<% title "Search" %>

<%= form_tag (params[:option] == 'graphs' ? create_search_path(anchor: "graphs") : create_search_path), method: "get" do |f| %>
  <div class="form-group">
    <%= label_tag :title %>
    <% if current_user&.can_use_regex_search? %>
      <%= check_box_tag :title_is_regex, 1, params[:title_is_regex] %> <span class="text-muted">regex</span>
      <%= check_box_tag :title_is_inverse_regex, 1, params[:title_is_inverse_regex] %> <span class="text-muted">invert</span>
    <% end %>
    <%= text_field_tag :title, params[:title], placeholder: "*", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= label_tag :body %>
    <%= check_box_tag :body_is_like, 1, params[:body_is_like] %>
    <span class="text-muted">
      LIKE (<a href="https://github.com/Charcoal-SE/metasmoke/wiki/FAQ:-search">?</a>)
    </span>
    <% if current_user&.can_use_regex_search? %>
      <%= check_box_tag :body_is_regex, 1, params[:body_is_regex] %> <span class="text-muted">regex</span>
      <%= check_box_tag :body_is_inverse_regex, 1, params[:body_is_inverse_regex] %> <span class="text-muted">invert</span>
    <% end %>
    <%= text_field_tag :body, params[:body], placeholder: "*", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= label_tag :username %>
    <% if current_user&.can_use_regex_search? %>
      <%= check_box_tag :username_is_regex, 1, params[:username_is_regex] %> <span class="text-muted">regex</span>
      <%= check_box_tag :username_is_inverse_regex, 1, params[:username_is_inverse_regex] %> <span class="text-muted">invert</span>
    <% end %>
    <%= text_field_tag :username, params[:username], placeholder: "*", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= label_tag :why %>
    <% if current_user&.can_use_regex_search? %>
      <%= check_box_tag :why_is_regex, 1, params[:why_is_regex] %> <span class="text-muted">regex</span>
      <%= check_box_tag :why_is_inverse_regex, 1, params[:why_is_inverse_regex] %> <span class="text-muted">invert</span>
    <% end %>
    <%= text_field_tag :why, params[:why], placeholder: "*", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= label_tag :or_search, "Use OR for text search (uses AND by default)" %>
    <%= check_box_tag :or_search, 1, params[:or_search] %>
  </div>
  <div class="form-group">
    <% h = HTMLEntities.new %>
    <%= label_tag :site %>
    <%= select_tag :site, options_for_select(Site.select(:site_name, :id).all.order(:site_name).map {|s| [h.decode(s.site_name), s.id] }, params[:site]), class: "form-control", include_blank: "All" %>
  </div>

  <div class="form-group">
    <%= label_tag :post_type %>
    <%= check_box_tag :post_type_include_unmatched, 1, params[:post_type_include_unmatched] %> <span class="text-muted">include unmatched</span>
    <%= select_tag :post_type, options_for_select(%i[question answer], params[:post_type]), class: "form-control", include_blank: "All" %>
  </div>

  <div class="form-group">
    <%= label_tag :feedback %>
    <%= select_tag :feedback, options_for_select(["true positive", "false positive", "NAA", "conflicted"], params[:feedback]), class: "form-control", include_blank: "All" %>
  </div>

  <div class="form-group">
    <%= label_tag :autoflagged %>
    <%= select_tag :autoflagged, options_for_select(["Yes", "No"], params[:autoflagged]), class: "form-control", include_blank: "All" %>
  </div>

  <div class="form-group">
    <%= label_tag :reason %>
    <%= select_tag :reason, options_from_collection_for_select(Reason.all.order(:reason_name), "id", "reason_name", params[:reason]), class: "form-control", include_blank: "All" %>
  </div>

  <div class="form-group">
    <%= label_tag :user_reputation %>
    <div class="form-group row">
      <div class="col-md-1">
        <%= select_tag :user_rep_direction, options_for_select(%w[== <= >=], params[:user_rep_direction]), include_blank: true,
                       class: "form-control" %>
      </div>

      <div class="col-md-1">
        <%= number_field_tag :user_reputation, params[:user_reputation], class: "form-control" %>
      </div>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :edited, "Edited" %>
    <%= check_box_tag :edited, 1, params[:edited] %>
  </div>

  <%= hidden_field_tag :option, params[:option] if params[:option] == 'graphs' %>

  <%= submit_tag "Search", class: "btn btn-primary" %>
<% end %>

app/views/search/search.html.erb
<% title "Search" %>

<%= form_tag (params[:option] == 'graphs' ? search_path(anchor: "graphs") : search_path), method: "get" do |f| %>
  <div class="form-group">
    <%= label_tag :title %>
    <% if current_user&.can_use_regex_search? %>
      <%= check_box_tag :title_is_regex, 1, params[:title_is_regex] %> <span class="text-muted">regex</span>
      <%= check_box_tag :title_is_inverse_regex, 1, params[:title_is_inverse_regex] %> <span class="text-muted">invert</span>
    <% end %>
    <%= text_field_tag :title, params[:title], placeholder: "*", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= label_tag :body %>
    <%= check_box_tag :body_is_like, 1, params[:body_is_like] %>
    <span class="text-muted">
      LIKE (<a href="https://github.com/Charcoal-SE/metasmoke/wiki/FAQ:-search">?</a>)
    </span>
    <% if current_user&.can_use_regex_search? %>
      <%= check_box_tag :body_is_regex, 1, params[:body_is_regex] %> <span class="text-muted">regex</span>
      <%= check_box_tag :body_is_inverse_regex, 1, params[:body_is_inverse_regex] %> <span class="text-muted">invert</span>
    <% end %>
    <%= text_field_tag :body, params[:body], placeholder: "*", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= label_tag :username %>
    <% if current_user&.can_use_regex_search? %>
      <%= check_box_tag :username_is_regex, 1, params[:username_is_regex] %> <span class="text-muted">regex</span>
      <%= check_box_tag :username_is_inverse_regex, 1, params[:username_is_inverse_regex] %> <span class="text-muted">invert</span>
    <% end %>
    <%= text_field_tag :username, params[:username], placeholder: "*", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= label_tag :why %>
    <% if current_user&.can_use_regex_search? %>
      <%= check_box_tag :why_is_regex, 1, params[:why_is_regex] %> <span class="text-muted">regex</span>
      <%= check_box_tag :why_is_inverse_regex, 1, params[:why_is_inverse_regex] %> <span class="text-muted">invert</span>
    <% end %>
    <%= text_field_tag :why, params[:why], placeholder: "*", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= label_tag :or_search, "Use OR for text search (uses AND by default)" %>
    <%= check_box_tag :or_search, 1, params[:or_search] %>
  </div>
  <div class="form-group">
    <% h = HTMLEntities.new %>
    <%= label_tag :site %>
    <%= select_tag :site, options_for_select(Site.select(:site_name, :id).all.order(:site_name).map {|s| [h.decode(s.site_name), s.id] }, params[:site]), class: "form-control", include_blank: "All" %>
  </div>

  <div class="form-group">
    <%= label_tag :post_type %>
    <%= check_box_tag :post_type_include_unmatched, 1, params[:post_type_include_unmatched] %> <span class="text-muted">include unmatched</span>
    <%= select_tag :post_type, options_for_select(%i[question answer], params[:post_type]), class: "form-control", include_blank: "All" %>
  </div>

  <div class="form-group">
    <%= label_tag :feedback %>
    <%= check_box_tag :has_no_feedback, 1, params[:has_no_feedback] %> <span class="text-muted">has no feedback?</span>
    <%= select_tag :feedback, options_for_select(["true positive", "false positive", "NAA", "conflicted"], params[:feedback]), class: "form-control", include_blank: "All" %>
  </div>

  <div class="form-group">
    <%= label_tag :autoflagged %>
    <%= select_tag :autoflagged, options_for_select(["Yes", "No"], params[:autoflagged]), class: "form-control", include_blank: "All" %>
  </div>

  <div class="form-group">
    <%= label_tag :reason %>
    <%= select_tag :reason, options_from_collection_for_select(Reason.all.order(:reason_name), "id", "reason_name", params[:reason]), class: "form-control", include_blank: "All" %>
  </div>

  <div class="form-group">
    <%= label_tag :user_reputation %>
    <div class="form-group row">
      <div class="col-md-1">
        <%= select_tag :user_rep_direction, options_for_select(%w[== <= >=], params[:user_rep_direction]), include_blank: true,
                       class: "form-control" %>
      </div>

      <div class="col-md-1">
        <%= number_field_tag :user_reputation, params[:user_reputation], class: "form-control" %>
      </div>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :edited, "Edited" %>
    <%= check_box_tag :edited, 1, params[:edited] %>
  </div>

  <%= hidden_field_tag :option, params[:option] if params[:option] == 'graphs' %>

  <%= submit_tag "Search", class: "btn btn-primary" %>
<% end %>

<br />

<% if @results.present? %>
  <ul class="nav nav-tabs post-table-nav-tabs search-results-nav-tabs post-table-nav-tabs-tp-fp-naa post-table-nav-tabs-has-graphs">
    <li role="presentation" class="nav-tab nav-tab-all-results <%= "active" if params[:option].nil? and (params[:feedback_filter].nil? or params[:feedback_filter] == 'all') %>">
      <%= link_to "Results (#{@total_count})", search_path(request.query_parameters.merge!({option: nil, feedback_filter: nil})) %>
    </li>
    <li class="nav-tab nav-tab-tp <%= 'active' if params[:feedback_filter] == 'tp' %>">
      <%= link_to "True positives (#{@counts_by_feedback[:is_tp]})", search_path(request.query_parameters.to_h.merge!({option: nil, feedback_filter: "tp"})) %>
    </li>
    <li class="nav-tab nav-tab-fp <%= 'active' if params[:feedback_filter] == 'fp' %>">
      <%= link_to "False positives (#{@counts_by_feedback[:is_fp]})", search_path(request.query_parameters.to_h.merge!({option: nil, feedback_filter: "fp"})) %>
    </li>
    <li class="nav-tab nav-tab-naa <%= 'active' if params[:feedback_filter] == 'naa' %>">
      <%= link_to "NAA (#{@counts_by_feedback[:is_naa]})", search_path(request.query_parameters.to_h.merge!({option: nil, feedback_filter: "naa"})) %>
    </li>
    <li role="presentation" class="nav-tab nav-tab-graphs <%= "active" if params[:option] == "graphs" %>">
      <%= link_to "Graphs", search_path(request.query_parameters.to_h.merge({option: "graphs", anchor: "graphs"})) %>
    </li>
  </ul>

  <% if params[:option].nil? %>
    <table class="table search-results-table posts-table">
      <%= render @results, collection: :post %>
    </table>
    <div class="text-center pagination-container">
      <%= will_paginate @results, renderer: BootstrapPagination::Rails %>
      <p class="text-muted link-to-json-format">
        <%= link_to "JSON (still subject to paging limits)", search_path(params: request.query_parameters, format: :json) %>
      </p>
    </div>
  <% else %>
    <div id="graphs">
      <% h = HTMLEntities.new %>
      <%= pie_chart @results.group(:site).count.map{ |k,v| {(k.nil? ? "Unknown" : h.decode(k.site_name))=>v} }.reduce(:merge).select{|k,v| k != "Unknown"}.sort_by {|k,v| v}.reverse %>

      <%= line_chart [{name: "True positives", data: @results.where(is_tp: true).group_by_day('`posts`.`created_at`', range: 1.month.ago.to_date..Time.now).count}, {name: "False positives", data: @results.where(is_fp: true).group_by_day('`posts`.`created_at`', range: 1.month.ago.to_date..Time.now).count}], colors: ["green", "red"], library: {"tooltip" => {'shared' => 'true'} } %>
    </div>
  <% end %>
<% end %>

<% if user_signed_in? && current_user.has_role?(:developer) %>
  <div class="panel panel-danger developer-tools searc-developer-tools">
    <div class="panel-heading">
      <h4 class="panel-title">Developer</h4>
    </div>
    <div class="panel-body">
      <ul>
        <li><%= link_to "Update site cache", url_for(controller: :developer, action: :update_sites), method: :post,
                data: { confirm: "You're a developer, so I should be assuming you know what you're doing, but: are you sure?" } %></li>
      </ul>
    </div>
  </div>
<% end %>

app/views/search/search_pending.html.erb
<% if @sid_ttl == -1 %>
<p>Your search is pending. Please keep reloading and eventually it'll work :)<p>
<% else %>
<p>Your search has been running for <%= SearchJob.search_job_timeout - @sid_ttl %> seconds...</p>
<% end %>