config/routes.rb
# frozen_string_literal: true

# routes.rb style guidance:
#
# - Root at the top
# - Unscoped routes next; group them logically
# - Throw everything else in a scope, alphabetically ordered.
# - Within a scope, unscoped routes go _after_ everything else.
# - Unscoped mounts at the bottom.
#
# RubyMine hint: Within the draw block, Ctrl-Shift-Minus followed by Ctrl-= (or cmd, whatever system you're on)
# will collapse everything and then expand the top level again so you just see unscoped routes plus scopes. Makes
# it much easier to see where everything is.
Rails.application.routes.draw do
  # Needs both with and without :as, ref Charcoal-SE/metasmoke#247
  root               to: 'dashboard#new_dash',  as: :dashboard
  root               to: 'dashboard#new_dash'

  resources :dumps

  get    'sites/dash',            to: 'dashboard#site_dash',        as: :site_dash

  get    'search',                to: 'search#index'
  get    'search_fast',           to: 'search#index_fast'
  get    'reasons',               to: 'dashboard#index',            as: :reasons
  get    'flagging',              to: 'flag_settings#dashboard',    as: :flagging

  get    'query-times',           to: 'dashboard#query_times',      as: :query_times
  post   'query-times/reset',     to: 'dashboard#reset_query_time', as: :reset_query_time

  post   'statistics.json',       to: 'statistics#create'
  post   'feedbacks.json',        to: 'feedbacks#create'
  post   'posts.json',            to: 'posts#create'
  post   'deletion_logs.json',    to: 'deletion_logs#create'
  post   'status-update.json',    to: 'status#status_update'

  delete 'feedback/:id/delete',   to: 'feedbacks#delete',           as: :delete_feedback

  devise_for :users, controllers: { sessions: 'custom_sessions', registrations: 'custom_registrations' }
  devise_scope :user do
    get  'users/2fa/login', to: 'custom_sessions#verify_2fa'
    post 'users/2fa/login', to: 'custom_sessions#verify_code'
  end

  scope 'abuse' do
    scope 'contacts' do
      root               to: 'abuse_contacts#index',   as: :abuse_contacts
      post   'new',      to: 'abuse_contacts#create',  as: :create_abuse_contact
      get    ':id',      to: 'abuse_contacts#show',    as: :abuse_contact
      get    ':id/edit', to: 'abuse_contacts#edit',    as: :edit_abuse_contact
      patch  ':id/edit', to: 'abuse_contacts#update',  as: :update_abuse_contact
      delete ':id',      to: 'abuse_contacts#destroy', as: :destroy_abuse_contact
    end

    scope 'statuses' do
      root               to: 'abuse_report_statuses#index',   as: :abuse_statuses
      post   'new',      to: 'abuse_report_statuses#create',  as: :create_abuse_status
      get    ':id',      to: 'abuse_report_statuses#show',    as: :abuse_status
      get    ':id/edit', to: 'abuse_report_statuses#edit',    as: :edit_abuse_status
      patch  ':id/edit', to: 'abuse_report_statuses#update',  as: :update_abuse_status
      delete ':id',      to: 'abuse_report_statuses#destroy', as: :destroy_abuse_status
    end

    scope 'reports' do
      root                   to: 'abuse_reports#index',         as: :abuse_reports
      get    'new',          to: 'abuse_reports#new',           as: :new_abuse_report
      post   'new',          to: 'abuse_reports#create',        as: :create_abuse_report
      get    'shared/:uuid', to: 'abuse_reports#public_link',   as: :shared_abuse_report
      get    ':id',          to: 'abuse_reports#show',          as: :abuse_report
      patch  ':id/edit',     to: 'abuse_reports#update',        as: :update_abuse_report
      post   ':id/status',   to: 'abuse_reports#update_status', as: :update_abuse_report_status
      delete ':id',          to: 'abuse_reports#destroy',       as: :destroy_abuse_report
    end

    scope 'comments' do
      post   'new',        to: 'abuse_comments#create',  as: :create_abuse_comment
      get    ':id',        to: 'abuse_comments#text',    as: :comment_abuse_text
      post   ':id/edit',   to: 'abuse_comments#update',  as: :edit_abuse_comment
      delete ':id/delete', to: 'abuse_comments#destroy', as: :delete_abuse_comment
    end
  end

  scope 'admin' do
    scope 'settings' do
      root                 to: 'site_settings#index',   as: :site_settings
      post   ':name',      to: 'site_settings#update',  as: :update_site_setting
      delete ':id/delete', to: 'site_settings#destroy', as: :destroy_site_setting
    end

    root                           to: 'admin#index'
    get    'invalidated',          to: 'admin#recently_invalidated'
    get    'user_feedback',        to: 'admin#user_feedback',               as: :admin_user_feedback
    get    'api_feedback',         to: 'admin#api_feedback'
    get    'flagged',              to: 'admin#flagged'
    post   'clear_flag',           to: 'admin#clear_flag'
    get    'users',                to: 'admin#users',                       as: :user_data
    get    'permissions',          to: 'admin#permissions',                 as: :admin_permissions
    put    'permissions/update',   to: 'admin#update_permissions'
    delete 'permissions/:user_id', to: 'admin#destroy_user'

    get    'invalidate_tokens',    to: 'authentication#invalidate_tokens'
    post   'invalidate_tokens',    to: 'authentication#send_invalidations'

    get    'new_key',              to: 'api_keys#new',                      as: :admin_new_key
    post   'new_key',              to: 'api_keys#create'
    get    'keys',                 to: 'api_keys#index'
    get    'keys/mine',            to: 'api_keys#mine'
    get    'edit_key/:id',         to: 'api_keys#edit'
    patch  'edit_key/:id',         to: 'api_keys#update'
    get    'owner_edit/:id',       to: 'api_keys#owner_edit'
    patch  'owner_edit/:id',       to: 'api_keys#owner_update'
    delete 'revoke_write',         to: 'api_keys#revoke_write_tokens'
    delete 'owner_revoke',         to: 'api_keys#owner_revoke'
    post   'keys/:id/trust',       to: 'api_keys#update_trust'
  end

  scope 'announcements' do
    root               to: 'announcements#index',  as: :announcements
    post ':id/expire', to: 'announcements#expire', as: :announcements_expire
    get  'new',        to: 'announcements#new'
    post 'new',        to: 'announcements#create'
    post 'enable',     to: 'users#set_announcement_emails'
  end

  scope 'api' do
    root                            to: 'api#api_docs',              as: :api_docs
    get  'filters',                 to: 'api#filter_generator'
    post 'filters',                 to: 'api#calculate_filter'

    get  'filter_fields',           to: 'api#filter_fields'
    get  'stats/last_week',         to: 'api#spam_last_week'
    get  'stats/detailed_ttd',      to: 'api#detailed_ttd'
    get  'smoke_detectors/status',  to: 'api#current_status'
    get  'smoke_detectors',         to: 'api#smoke_detectors'
    get  'posts/urls',              to: 'api#posts_by_url'
    post 'posts/urls',              to: 'api#posts_by_url'
    get  'posts/feedback',          to: 'api#posts_by_feedback'
    get  'posts/undeleted',         to: 'api#undeleted_posts'
    get  'posts/site',              to: 'api#posts_by_site'
    get  'posts/between',           to: 'api#posts_by_daterange'
    get  'posts/search',            to: 'api#search_posts'
    get  'posts/:ids',              to: 'api#posts'
    get  'post/:id/feedback',       to: 'api#post_feedback'
    get  'post/:id/reasons',        to: 'api#post_reasons'
    get  'post/:id/valid_feedback', to: 'api#post_valid_feedback'
    get  'reasons',                 to: 'api#all_reasons'
    get  'reasons/:ids',            to: 'api#reasons'
    get  'reason/:id/posts',        to: 'api#reason_posts'
    get  'blacklist',               to: 'api#blacklisted_websites'
    get  'users',                   to: 'api#users',                 as: :api_users
    get  'users/code_privileged',   to: 'api#users_with_code_privs'
    get  'post/:id/domains',        to: 'api#post_domains',          as: :api_post_domains
    get  'domains/:id/tags',        to: 'api#domain_tags',           as: :api_domain_tags

    post 'w/post/:id/feedback',     to: 'api#create_feedback'
    post 'w/post/report',           to: 'api#report_post'
    post 'w/post/:id/spam_flag',    to: 'api#spam_flag'
    post 'w/post/:id/deleted',      to: 'api#post_deleted'
    post 'w/domains/:id/add_tag',   to: 'api#add_domain_tag',        as: :api_add_domain_tag

    post 'graphql',                 to: 'graphql#execute',           as: :graphql
    get 'graphql',                  to: 'graphql#query',             as: :query_graphql
  end
  mount GraphiQL::Rails::Engine,  at: '/api/graphiql',                 graphql_path: '/api/graphql', query_params: true

  scope 'authentication' do
    get 'status',                to: 'authentication#status', as: :authentication_status
    get 'redirect_target',       to: 'authentication#redirect_target'
    get 'login_redirect_target', to: 'authentication#login_redirect_target'
  end

  scope 'channels' do
    post 'receive_email', to: 'channels#receive_email',     as: :channels_receive_email
    get  'email',         to: 'channels#get_email_address', as: :channels_email
    get  'link',          to: 'channels#show_link',         as: :channels_link
  end

  scope 'comments' do
    post 'new',          to: 'post_comments#create',  as: :create_comment
    get  ':id',          to: 'post_comments#text',    as: :comment_text
    post ':id/edit',     to: 'post_comments#update',  as: :edit_comment
    delete ':id/delete', to: 'post_comments#destroy', as: :delete_comment
  end

  scope 'data' do
    authenticate(:user, ->(user) { user.has_role?(:core) }) do
      mount Blazer::Engine, at: 'sql'
    end
  end

  scope 'dev' do
    post 'update_sites',     to: 'developer#update_sites',          as: :dev_update_sites
    get  'prod_log',         to: 'developer#production_log',        as: :dev_prod_log

app/models/abuse_report.rb
# frozen_string_literal: true

class AbuseReport < ApplicationRecord
  include Websocket

  belongs_to :user
  belongs_to :reportable, polymorphic: true
  belongs_to :contact, class_name: 'AbuseContact', foreign_key: 'abuse_contact_id'
  belongs_to :status, class_name: 'AbuseReportStatus', foreign_key: 'abuse_report_status_id'
  has_many :comments, class_name: 'AbuseComment', dependent: :destroy

  validates :reportable_type, presence: true, inclusion: { in: %w[SpamDomain Post DomainTag] }
  validates_presence_of :reportable, message: proc { |s|
                                                "cannot be invalid item #{s.reportable_type}##{s.reportable_id}"
                                              }

  before_validation do
    self.status = AbuseReportStatus[AbuseReportStatus::DEFAULT_STATUS] unless status.present?

    self.uuid = SecureRandom.uuid unless uuid.present?
  end

  def self.update_stale_reports
    stale_status = AbuseReportStatus['Stale']
    open_status = AbuseReportStatus['Open']

    AbuseReport.where(status: open_status).each do |ar|
      last_update = (ar.comments.map(&:created_at) + [ar.created_at]).max
      ar.update(status: stale_status) if last_update <= 2.weeks.ago
    end
  end
end

app/controllers/abuse_reports_controller.rb
# frozen_string_literal: true

class AbuseReportsController < ApplicationController
  before_action :verify_core, except: [:public_link]
  before_action :set_report, except: %i[index new create public_link]
  before_action :verify_access, except: %i[index new create show public_link]
  before_action :verify_admin, only: [:destroy]

  def index
    case params[:filter]
    when 'closed'
      ids = [AbuseReportStatus['Closed: Successful'].id, AbuseReportStatus['Closed: Unsuccessful'].id]
      @reports = AbuseReport.where(abuse_report_status_id: ids).paginate(page: params[:page], per_page: 90)
    when 'stale'
      @reports = AbuseReport.where(status: AbuseReportStatus['Stale']).paginate(page: params[:page], per_page: 90)
    else # includes when 'open'
      @reports = AbuseReport.where(status: AbuseReportStatus['Open']).paginate(page: params[:page], per_page: 90)
    end
  end

  def new; end

  def create
    @report = AbuseReport.new report_params.merge(user: current_user)
    if @report.save
      flash[:success] = "Opened new abuse report ##{@report.id}."
      redirect_to abuse_report_path(@report)
    else
      flash[:danger] = "Failed to open new report:\n#{@report.errors.full_messages.join("\n")}"
      redirect_to new_abuse_report_path(reportable_type: @report.reportable_type, reportable_id: @report.reportable_id)
    end
  end

  def show
    @reportable_path = {
      'DomainTag' => domain_tag_path(@report.reportable),
      'Post' => post_path(@report.reportable),
      'SpamDomain' => spam_domain_path(@report.reportable)
    }[@report.reportable_type]
  end

  def public_link
    @report = AbuseReport.find_by_uuid params[:uuid]
    @reportable_path = {
      'DomainTag' => domain_tag_path(@report.reportable),
      'Post' => post_path(@report.reportable),
      'SpamDomain' => spam_domain_path(@report.reportable)
    }[@report.reportable_type]
    render :show
  end

  def update
    if @report.update report_params
      flash[:success] = 'Updated report.'
    else
      flash[:danger] = 'Failed to update report.'
    end
    redirect_back fallback_location: abuse_report_path(@report)
  end

  def update_status
    old_status = @report.status.name
    status = AbuseReportStatus.find params[:status_id]
    new_status = status.name
    if @report.update status: status
      AbuseComment.create user: User.find(-1), report: @report,
                          text: "**#{current_user.username}** updated the status from **#{old_status}** to **#{new_status}**"
      flash[:success] = 'Updated status.'
    else
      flash[:danger] = 'Failed to update status.'
    end
    redirect_back fallback_location: abuse_report_path(@report)
  end

  def destroy
    if @report.destroy
      flash[:success] = 'Removed report.'
      redirect_to abuse_reports_path
    else
      flash[:danger] = 'Failed to remove report.'
      redirect_to abuse_report_path(@report)
    end
  end

  private

  def report_params
    params.require(:abuse_report).permit(:reportable_type, :reportable_id, :abuse_contact_id, :details)
  end

  def set_report
    @report = AbuseReport.find params[:id]
  end

  def verify_access
    return if current_user == @report.user || current_user&.has_role?(:admin)

    not_found
  end
end

app/helpers/abuse_reports_helper.rb
# frozen_string_literal: true

module AbuseReportsHelper
end

app/views/abuse_reports/_form.html.erb
<%= form_for report, url: url do |f| %>
  <div class="field row">
    <div class="col-md-4">
      <%= f.label :reportable_type do %>
        <span class="glyphicon glyphicon-question-sign"></span> What are you reporting? *
      <% end %><br/>
      <%= f.select :reportable_type,
          options_for_select([%w[SpamDomain SpamDomain], %w[Post Post], %w[DomainTag DomainTag]], report.reportable_type),
          { include_blank: true }, class: 'form-control' %>
    </div>
    <div class="col-md-8">
      <%= f.label :reportable_id, raw('&nbsp;') %><br/>
      <div class="input-group">
        <span class="input-group-addon">#</span>
        <%= f.number_field :reportable_id, class: 'form-control' %>
      </div>
    </div>
  </div><br/>
  <div class="field">
    <%= f.label :abuse_contact_id do %>
      <span class="glyphicon glyphicon-user"></span> Who are you reporting it to? *
    <% end %>
    <span class="small text-muted">Not listed? <a href="#" data-toggle="modal" data-target="#create-contact-modal">Create it now.</a></span>
    <br/>
    <%= f.select :abuse_contact_id, options_for_select(AbuseContact.all.map { |ac| [ac.name, ac.id] }, report.abuse_contact_id || flash[:abuse_contact_id]),
          { include_blank: true }, class: 'form-control selectpicker',
                                   data: { live_search: true, actions_box: true, dropup_auto: false } %>
  </div><br/>
  <div class="field">
    <%= f.label :details do %>
      <span class="glyphicon glyphicon-align-center"></span> Any more details you want to add?
    <% end %>
    <span class="small text-muted">Optional; Markdown supported. If you're sending the report via email you may want to
    include its text here.</span><br/>
    <%= f.text_area :details, rows: 7, cols: 100, class: 'form-control' %>
  </div><br/>
  <div class="actions">
    <%= f.submit 'Save Report', class: 'btn btn-success' %>
  </div>
<% end %>

<div class="modal fade" id="create-contact-modal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">New Abuse Contact</h4>
      </div>
      <div class="modal-body">
        <%= render 'abuse_contacts/form', contact: AbuseContact.new, url: create_abuse_contact_path %>
      </div>
    </div>
  </div>
</div>

app/views/abuse_reports/_list.html.erb
<% abuse_reports = item.abuse_reports %>

<% if abuse_reports.count > 0 %>
  <p>Abuse Reports:
    <%= raw(abuse_reports.map do |abuse_report| %>
      <% link_to abuse_report do %>
        #<%= abuse_report.id %>
      <% end %>
    <% end.join(', ')) %>
    &nbsp;&nbsp;|&nbsp;&nbsp;
    <%= link_to new_abuse_report_path(reportable_type: item.class.to_s, reportable_id: item.id), class: 'text-muted' do %>
      <span class="glyphicon glyphicon-file"></span> Create Abuse Report
    <% end %>
  </p>
<% else %>
  <p><%= link_to new_abuse_report_path(reportable_type: item.class.to_s, reportable_id: item.id) do %>
    <span class="glyphicon glyphicon-file"></span> Create Abuse Report
  <% end %></p>
<% end %>

app/views/abuse_reports/_report.html.erb
<div class="col-md-4">
  <div class="panel panel-default abuse-report">
    <div class="panel-body">
      <h3>
        <%= render 'abuse_report_statuses/status', status: report.status, nl: true %>
        <%= link_to abuse_report_path(report) do %>
          #<%= report.id %>
        <% end %>
      </h3>
      <p>
        Reported to
        <strong><%= report.contact.present? ? link_to(report.contact.name, abuse_contact_path(report.contact)) : 'No contact stored' %></strong>
        by
        <strong><%= report.user.present? ? report.user.username : 'User not stored' %></strong>
        <%= time_ago_in_words report.created_at %> ago
      </p>
    </div>
  </div>
</div>

app/views/abuse_reports/index.html.erb
<h1>Abuse Reports</h1>
<p>One giant list of all the abuse reports, ever.</p>

<ul class="nav nav-tabs">
  <li class="<%= 'active' if params[:filter] == 'open' || params[:filter].nil? %>"><%= link_to 'Open', abuse_reports_path(filter: 'open') %></li>
  <li class="<%= 'active' if params[:filter] == 'stale' %>"><%= link_to 'Stale', abuse_reports_path(filter: 'stale') %></li>
  <li class="<%= 'active' if params[:filter] == 'closed' %>"><%= link_to 'Closed', abuse_reports_path(filter: 'closed') %></li>
</ul>

<% @reports.in_groups_of(3).map(&:compact).each do |g| %>
  <div class="row">
    <% g.each do |r| %>
      <%= render 'report', report: r %>
    <% end %>
  </div>
<% end %>

<%= will_paginate @reports, renderer: BootstrapPagination::Rails %>

app/views/abuse_reports/new.html.erb
<h1>New Abuse Report</h1>

<%= render 'form', report: AbuseReport.new(reportable_type: params[:reportable_type], reportable_id: params[:reportable_id]),
                url: create_abuse_report_path %>

app/views/abuse_reports/show.html.erb
<h1 class="report-title">
  <%= render 'abuse_report_statuses/status', status: @report.status, nl: true %>
  <span class="text-muted">#<%= @report.id %>:</span>
  <% if @report.reportable_type == 'SpamDomain' %>
    <%= @report.reportable.domain %>
  <% elsif @report.reportable_type == 'Post' %>
    <%= @report.reportable.title %>
  <% elsif @report.reportable_type == 'DomainTag' %>
    <code>#<%= @report.reportable.name %></code>
  <% end %>
</h1>

<% if current_user == @report.user || current_user&.has_role?(:admin) %>
  <p>
    <a href="#" data-toggle="modal" data-target="#edit-report-modal">Edit</a>
    <% if current_user&.has_role?(:admin) %>
      &middot;
      <%= link_to 'Delete', destroy_abuse_report_path(@report), class: 'text-danger', method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>
  </p>

  <p>
    <a href="#" data-toggle="modal" data-target="#report-share-link">
      <span class="glyphicon glyphicon-link"></span> Get shareable link
    </a>
  </p>

  <%= form_tag update_abuse_report_status_path(@report), class: 'form-inline' do %>
    <%= label_tag :status_id, 'Update report status:' %>
    <%= select_tag :status_id, options_from_collection_for_select(AbuseReportStatus.all, 'id', 'name'), include_blank: true,
                   class: 'form-control input-sm' %>
    <%= submit_tag 'Update', class: 'btn btn-success btn-sm' %>
  <% end %><br/>
<% end %>

<p>
  <%= link_to @reportable_path do %>
    <span class="glyphicon glyphicon-paperclip"></span> Go to reported item
  <% end %>
</p>

<div class="panel panel-info">
  <div class="panel-heading">
    Reported to <strong><%= @report.contact.present? ? link_to(@report.contact.name, abuse_contact_path(@report.contact)) : 'No contact stored' %></strong>
  </div>
</div>

<div class="panel panel-default">
  <div class="panel-heading">
    Opened by <strong><%= @report.user.username %></strong> <%= time_ago_in_words @report.created_at %> ago
  </div>
  <div class="panel-body">
    <%= safe_render_markdown(@report.details.present? ? @report.details : 'No report details stored', scrubber: Announcement.scrubber) %>
  </div>
</div>

<% @report.comments.each do |c| %>
    <%= render 'abuse_comments/comment', comment: c %>
<% end %>

<% if current_user&.has_role?(:core) %>
  <p><a href="#" class="new-comment"><span class="glyphicon glyphicon-plus"></span> Add a comment</a></p>
<% end %>

<div class="add-comment">
  <%= form_for AbuseComment.new, url: create_abuse_comment_path do |f| %>
    <%= f.hidden_field :abuse_report_id, value: @report.id %>
    <div class="field">
      <%= f.text_area :text, rows: 3, cols: 100, placeholder: 'Useful information about this report that others might need...',
                      class: 'form-control' %>
    </div>
    <div class="actions">
      <%= f.submit 'Add Comment', class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>

<!-- - -->

<div class="modal modal-lg fade" id="edit-report-modal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Edit Report</h4>
      </div>
      <div class="modal-body">
        <%= render 'form', report: @report, url: update_abuse_report_path(@report) %>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="report-share-link">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Public Shareable Link</h4>
      </div>
      <div class="modal-body">
        <label for="public-link"><span class="glyphicon glyphicon-link"></span> Link</label><br/>
        <input id="public-link" class="form-control" type="text" value="<%= shared_abuse_report_url(@report.uuid) %>" />
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-success" data-dismiss="modal">OK</button>
      </div>
    </div>
  </div>
</div>