config/routes.rb
# frozen_string_literal: true

# routes.rb style guidance:
#
# - Root at the top
# - Unscoped routes next; group them logically
# - Throw everything else in a scope, alphabetically ordered.
# - Within a scope, unscoped routes go _after_ everything else.
# - Unscoped mounts at the bottom.
#
# RubyMine hint: Within the draw block, Ctrl-Shift-Minus followed by Ctrl-= (or cmd, whatever system you're on)
# will collapse everything and then expand the top level again so you just see unscoped routes plus scopes. Makes
# it much easier to see where everything is.
Rails.application.routes.draw do
  # Needs both with and without :as, ref Charcoal-SE/metasmoke#247
  root               to: 'dashboard#new_dash',  as: :dashboard
  root               to: 'dashboard#new_dash'

  resources :dumps

  get    'sites/dash',            to: 'dashboard#site_dash',        as: :site_dash

  get    'search',                to: 'search#index'
  get    'search_fast',           to: 'search#index_fast'
  get    'reasons',               to: 'dashboard#index',            as: :reasons
  get    'flagging',              to: 'flag_settings#dashboard',    as: :flagging

  get    'query-times',           to: 'dashboard#query_times',      as: :query_times
  post   'query-times/reset',     to: 'dashboard#reset_query_time', as: :reset_query_time

  post   'statistics.json',       to: 'statistics#create'
  post   'feedbacks.json',        to: 'feedbacks#create'
  post   'posts.json',            to: 'posts#create'
  post   'deletion_logs.json',    to: 'deletion_logs#create'
  post   'status-update.json',    to: 'status#status_update'

  delete 'feedback/:id/delete',   to: 'feedbacks#delete',           as: :delete_feedback

  devise_for :users, controllers: { sessions: 'custom_sessions', registrations: 'custom_registrations' }
  devise_scope :user do
    get  'users/2fa/login', to: 'custom_sessions#verify_2fa'
    post 'users/2fa/login', to: 'custom_sessions#verify_code'
  end

  scope 'abuse' do
    scope 'contacts' do
      root               to: 'abuse_contacts#index',   as: :abuse_contacts
      post   'new',      to: 'abuse_contacts#create',  as: :create_abuse_contact
      get    ':id',      to: 'abuse_contacts#show',    as: :abuse_contact
      get    ':id/edit', to: 'abuse_contacts#edit',    as: :edit_abuse_contact
      patch  ':id/edit', to: 'abuse_contacts#update',  as: :update_abuse_contact
      delete ':id',      to: 'abuse_contacts#destroy', as: :destroy_abuse_contact
    end

    scope 'statuses' do
      root               to: 'abuse_report_statuses#index',   as: :abuse_statuses
      post   'new',      to: 'abuse_report_statuses#create',  as: :create_abuse_status
      get    ':id',      to: 'abuse_report_statuses#show',    as: :abuse_status
      get    ':id/edit', to: 'abuse_report_statuses#edit',    as: :edit_abuse_status
      patch  ':id/edit', to: 'abuse_report_statuses#update',  as: :update_abuse_status
      delete ':id',      to: 'abuse_report_statuses#destroy', as: :destroy_abuse_status
    end

    scope 'reports' do
      root                   to: 'abuse_reports#index',         as: :abuse_reports
      get    'new',          to: 'abuse_reports#new',           as: :new_abuse_report
      post   'new',          to: 'abuse_reports#create',        as: :create_abuse_report
      get    'shared/:uuid', to: 'abuse_reports#public_link',   as: :shared_abuse_report
      get    ':id',          to: 'abuse_reports#show',          as: :abuse_report
      patch  ':id/edit',     to: 'abuse_reports#update',        as: :update_abuse_report
      post   ':id/status',   to: 'abuse_reports#update_status', as: :update_abuse_report_status
      delete ':id',          to: 'abuse_reports#destroy',       as: :destroy_abuse_report
    end

    scope 'comments' do
      post   'new',        to: 'abuse_comments#create',  as: :create_abuse_comment
      get    ':id',        to: 'abuse_comments#text',    as: :comment_abuse_text
      post   ':id/edit',   to: 'abuse_comments#update',  as: :edit_abuse_comment
      delete ':id/delete', to: 'abuse_comments#destroy', as: :delete_abuse_comment
    end
  end

  scope 'admin' do
    scope 'settings' do
      root                 to: 'site_settings#index',   as: :site_settings
      post   ':name',      to: 'site_settings#update',  as: :update_site_setting
      delete ':id/delete', to: 'site_settings#destroy', as: :destroy_site_setting
    end

    root                           to: 'admin#index'
    get    'invalidated',          to: 'admin#recently_invalidated'
    get    'user_feedback',        to: 'admin#user_feedback',               as: :admin_user_feedback
    get    'api_feedback',         to: 'admin#api_feedback'
    get    'flagged',              to: 'admin#flagged'
    post   'clear_flag',           to: 'admin#clear_flag'
    get    'users',                to: 'admin#users',                       as: :user_data
    get    'permissions',          to: 'admin#permissions',                 as: :admin_permissions
    put    'permissions/update',   to: 'admin#update_permissions'
    delete 'permissions/:user_id', to: 'admin#destroy_user'

    get    'invalidate_tokens',    to: 'authentication#invalidate_tokens'
    post   'invalidate_tokens',    to: 'authentication#send_invalidations'

    get    'new_key',              to: 'api_keys#new',                      as: :admin_new_key
    post   'new_key',              to: 'api_keys#create'
    get    'keys',                 to: 'api_keys#index'
    get    'keys/mine',            to: 'api_keys#mine'
    get    'edit_key/:id',         to: 'api_keys#edit'
    patch  'edit_key/:id',         to: 'api_keys#update'
    get    'owner_edit/:id',       to: 'api_keys#owner_edit'
    patch  'owner_edit/:id',       to: 'api_keys#owner_update'
    delete 'revoke_write',         to: 'api_keys#revoke_write_tokens'
    delete 'owner_revoke',         to: 'api_keys#owner_revoke'
    post   'keys/:id/trust',       to: 'api_keys#update_trust'
  end

  scope 'announcements' do
    root               to: 'announcements#index',  as: :announcements
    post ':id/expire', to: 'announcements#expire', as: :announcements_expire
    get  'new',        to: 'announcements#new'
    post 'new',        to: 'announcements#create'
    post 'enable',     to: 'users#set_announcement_emails'
  end

  scope 'api' do
    root                            to: 'api#api_docs',              as: :api_docs
    get  'filters',                 to: 'api#filter_generator'
    post 'filters',                 to: 'api#calculate_filter'

    get  'filter_fields',           to: 'api#filter_fields'
    get  'stats/last_week',         to: 'api#spam_last_week'
    get  'stats/detailed_ttd',      to: 'api#detailed_ttd'
    get  'smoke_detectors/status',  to: 'api#current_status'
    get  'smoke_detectors',         to: 'api#smoke_detectors'
    get  'posts/urls',              to: 'api#posts_by_url'
    post 'posts/urls',              to: 'api#posts_by_url'
    get  'posts/feedback',          to: 'api#posts_by_feedback'
    get  'posts/undeleted',         to: 'api#undeleted_posts'
    get  'posts/site',              to: 'api#posts_by_site'
    get  'posts/between',           to: 'api#posts_by_daterange'
    get  'posts/search',            to: 'api#search_posts'
    get  'posts/:ids',              to: 'api#posts'
    get  'post/:id/feedback',       to: 'api#post_feedback'
    get  'post/:id/reasons',        to: 'api#post_reasons'
    get  'post/:id/valid_feedback', to: 'api#post_valid_feedback'
    get  'reasons',                 to: 'api#all_reasons'
    get  'reasons/:ids',            to: 'api#reasons'
    get  'reason/:id/posts',        to: 'api#reason_posts'
    get  'blacklist',               to: 'api#blacklisted_websites'
    get  'users',                   to: 'api#users',                 as: :api_users
    get  'users/code_privileged',   to: 'api#users_with_code_privs'
    get  'post/:id/domains',        to: 'api#post_domains',          as: :api_post_domains
    get  'domains/:id/tags',        to: 'api#domain_tags',           as: :api_domain_tags

    post 'w/post/:id/feedback',     to: 'api#create_feedback'
    post 'w/post/report',           to: 'api#report_post'
    post 'w/post/:id/spam_flag',    to: 'api#spam_flag'
    post 'w/post/:id/deleted',      to: 'api#post_deleted'
    post 'w/domains/:id/add_tag',   to: 'api#add_domain_tag',        as: :api_add_domain_tag

    post 'graphql',                 to: 'graphql#execute',           as: :graphql
    get 'graphql',                  to: 'graphql#query',             as: :query_graphql
  end
  mount GraphiQL::Rails::Engine,  at: '/api/graphiql',                 graphql_path: '/api/graphql', query_params: true

  scope 'authentication' do
    get 'status',                to: 'authentication#status', as: :authentication_status
    get 'redirect_target',       to: 'authentication#redirect_target'
    get 'login_redirect_target', to: 'authentication#login_redirect_target'
  end

  scope 'channels' do
    post 'receive_email', to: 'channels#receive_email',     as: :channels_receive_email
    get  'email',         to: 'channels#get_email_address', as: :channels_email
    get  'link',          to: 'channels#show_link',         as: :channels_link
  end

  scope 'comments' do
    post 'new',          to: 'post_comments#create',  as: :create_comment
    get  ':id',          to: 'post_comments#text',    as: :comment_text
    post ':id/edit',     to: 'post_comments#update',  as: :edit_comment
    delete ':id/delete', to: 'post_comments#destroy', as: :delete_comment
  end

  scope 'data' do
    authenticate(:user, ->(user) { user.has_role?(:core) }) do
      mount Blazer::Engine, at: 'sql'
    end
  end

  scope 'dev' do
    post 'update_sites',     to: 'developer#update_sites',          as: :dev_update_sites
    get  'prod_log',         to: 'developer#production_log',        as: :dev_prod_log

app/models/domain_tag.rb
# frozen_string_literal: true

class DomainTag < ApplicationRecord
  include Websocket

  has_and_belongs_to_many :spam_domains, after_add: :send_whitelist
  has_and_belongs_to_many :posts
  has_many :abuse_reports, as: :reportable

  scope(:standard, -> { where(special: false) })
  scope(:special, -> { where(special: true) })

  def send_whitelist
    ActionCable.server.broadcast('smokedetector_messages', domain_whitelist: 'refresh') if name == 'whitelisted'
  end

  def merge_into(master)
    master.spam_domains += (spam_domains.to_a - master.spam_domains.to_a)
    master.posts += (posts.to_a - master.posts.to_a)

    spam_domains.clear
    posts.clear

    destroy
  end
end

app/controllers/domain_tags_controller.rb
# frozen_string_literal: true

class DomainTagsController < ApplicationController
  before_action :authenticate_user!,
                only: %i[add remove edit update destroy add_post remove_post submit_mass_tag add_review]
  before_action :verify_core, only: %i[add remove edit update add_post remove_post submit_mass_tag add_review]
  before_action :verify_admin, only: [:destroy]
  before_action :set_domain_tag, only: %i[show edit update destroy]
  before_action :verify_developer, only: [:merge]

  def index
    @tags = if params[:filter].present? && params[:include_special].present?
              DomainTag.all.where('name LIKE ?', "%#{params[:filter]}%")
            elsif params[:filter].present?
              DomainTag.standard.where('name LIKE ?', "%#{params[:filter]}%")
            else
              DomainTag.standard
            end.order(name: :asc).paginate(page: params[:page], per_page: 100)
    @counts = DomainTag.where(id: @tags.map(&:id)).joins(:spam_domains).group(Arel.sql('domain_tags.id')).count
  end

  def add
    @tag = DomainTag.find_or_create_by name: params[:tag_name]
    @domain = SpamDomain.find params[:domain_id]
    if @domain.domain_tags.include? @tag
      flash[:danger] = "This domain already has the tag '#{@tag.name}'."
    else
      @domain.domain_tags << @tag
    end
    redirect_to spam_domain_path(@domain)
  end

  def add_review
    @tag = DomainTag.find_or_create_by name: params[:tag_name]
    @domain = SpamDomain.find params[:domain_id]
    @domain.domain_tags << @tag unless @domain.domain_tags.include? @tag
    render 'domain_tags/_tag', locals: { tag: @tag, domain: @domain }, layout: nil
  end

  def add_post
    @tag = DomainTag.find_or_create_by name: params[:tag_name]
    @post = Post.find params[:post_id]
    if @post.post_tags.include? @tag
      flash[:danger] = "This post already has the tag '#{@tag.name}'."
    else
      @post.post_tags << @tag
    end
    redirect_to post_path(@post)
  end

  def remove
    @domain = SpamDomain.find params[:domain_id]
    @domain.domain_tags.delete(DomainTag.find_by(name: params[:tag_name]))
    redirect_to spam_domain_path(@domain)
  end

  def remove_post
    @post = Post.find params[:post_id]
    @post.post_tags.delete(DomainTag.find_by(name: params[:tag_name]))
    redirect_back fallback_location: post_path(@post)
  end

  def show
    if params[:what] == 'posts'
      @posts = @tag.posts.includes_for_post_row.paginate(page: params[:page], per_page: 100)
      @sites = Site.where(id: @posts.map(&:site_id))
    else
      @counts_summary = %i[all tp fp naa].map do |t|
        [t, Post.joins(spam_domains: :domain_tags).where(domain_tags: { id: @tag.id }).distinct.send(t).count]
      end.to_h
      @domains = @tag.spam_domains.paginate(page: params[:page], per_page: 100)
      @counts = SpamDomain.where(id: @domains.map(&:id)).joins(:posts).group(Arel.sql('spam_domains.id')).count
      @counts_per_domain = %i[tp fp naa].map do |t|
        [t, @tag.spam_domains.joins(:posts).where(posts: { "is_#{t}": true }).group('spam_domains.id').count]
      end.to_h
    end
  end

  def edit; end

  def update
    if @tag.update tag_params
      flash[:success] = 'Updated tag.'
      redirect_to domain_tag_path(@tag)
    else
      flash[:danger] = 'Failed to update tag.'
      render :edit
    end
  end

  def destroy
    if @tag.destroy
      flash[:success] = 'Removed tag.'
      redirect_to domain_tags_path
    else
      flash[:danger] = 'Failed to remove tag.'
      render :show
    end
  end

  def mass_tagging
    @domains = if params[:filter].present?
                 mass_tag_filter params[:filter]
               else
                 SpamDomain.all
               end.paginate(page: params[:page], per_page: 100)
    @counts = SpamDomain.where(id: @domains.map(&:id)).joins(:posts).group(Arel.sql('spam_domains.id')).count
    @taggable = params[:filter].present?
  end

  def submit_mass_tag
    @domains = mass_tag_filter params[:filter]
    @tag = DomainTag.find_or_create_by name: params[:tag]
    pairs = @domains.map { |d| [@tag, d] }
    ApplicationRecord.mass_habtm 'domain_tags_spam_domains', 'domain_tag', 'spam_domain', pairs
    flash[:success] = 'Tag applied to selected posts.'
    redirect_to domain_tags_mass_tagging_path(filter: params[:filter])
  end

  def merge
    source = DomainTag.find params[:source_id]
    target = DomainTag.find params[:target_id]

    source.merge_into target

    flash[:success] = 'Tag merge completed.'
    redirect_to domain_tag_path(target)
  end

  private

  def set_domain_tag
    @tag = DomainTag.find params[:id]
  end

  def tag_params
    params.require(:domain_tag).permit(:name, :description)
  end

  def mass_tag_filter(filter_param)
    SpamDomain.where('domain LIKE ?', ApplicationRecord.sanitize_like(filter_param).tr('*', '%'))
  end
end

app/helpers/domain_tags_helper.rb
# frozen_string_literal: true

module DomainTagsHelper
end

app/views/domain_tags/_post_tag.html.erb
<% post ||= nil %>
<div class="label label-info tag-label" data-toggle="tooltip" title="<%= tag.description %>">
  <%= link_to domain_tag_path(tag), class: 'domain-tag' do %>
    #<%= tag.name %>
  <% end %>
  <% unless post.nil? %>
    <%= form_tag remove_post_tag_path, method: :post do %>
      <%= hidden_field_tag :post_id, post.id %>
      <%= hidden_field_tag :tag_name, tag.name %>
      <span class="text-danger form-submit">&times;</span>
    <% end %>
  <% end %>
</div>

app/views/domain_tags/_tag.html.erb
<% domain ||= nil %>
<div class="label label-<%= tag.special? ? 'warning' : 'info' %> tag-label" data-toggle="tooltip" title="<%= tag.description %>">
  <%= link_to domain_tag_path(tag), class: 'domain-tag' do %>
    #<%= tag.name %>
  <% end %>
  <% if domain.present? && !tag.special %>
    <%= form_tag remove_domain_tag_path, method: :post do %>
      <%= hidden_field_tag :domain_id, domain.id %>
      <%= hidden_field_tag :tag_name, tag.name %>
      <span class="text-danger form-submit">&times;</span>
    <% end %>
  <% end %>
</div>

app/views/domain_tags/edit.html.erb
<h3>Editing Domain Tag: <%= render 'tag', tag: @tag %></h3>
<%= form_for @tag, url: update_domain_tag_path do |f| %>
  <div class="field">
    <%= f.label :name %><br/>
    <%= f.text_field :name, class: 'form-control' %>
  </div><br/>

  <div class="field">
    <%= f.label :description %><br/>
    <%= f.text_area :description, rows: 5, cols: 70, class: 'form-control' %>
  </div><br/>

  <div class="actions">
    <%= f.submit 'Save', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/domain_tags/index.html.erb
<h3>Domain Tagging</h3>

<%= form_tag domain_tags_path, method: :get, class: 'form-inline' do %>
  <%= text_field_tag :filter, params[:filter], class: 'form-control input-sm', placeholder: 'Search for tags' %>
  <%= check_box_tag :include_special, '1', params[:include_special] == '1' %>
  <%= label_tag :include_special, 'Include special tags?' %>
  <%= submit_tag 'Search', class: 'btn btn-primary btn-sm' %>
<% end %>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Tag</th>
      <th>Domains</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @tags.each do |t| %>
      <tr>
        <td><span class="label label-<%= t.special? ? 'warning' : 'info' %>">#<%= t.name %></span> <span class="text-muted"><%= t.description&.truncate(100) %></span></td>
        <td><%= @counts[t.id] || 0 %></td>
        <td><%= link_to 'Details', domain_tag_path(t) %></td>
        <% if user_signed_in? && current_user.has_role?(:core) %>
          <td><%= link_to 'Edit', edit_domain_tag_path(t) %></td>
        <% end %>
        <% if user_signed_in? && current_user.has_role?(:admin) %>
          <td><%= link_to 'Delete', destroy_domain_tag_path(t), method: :delete, class: 'text-danger',
                                               data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @tags, renderer: BootstrapPagination::Rails %>

app/views/domain_tags/mass_tagging.html.erb
<h3>Mass Tagging</h3>
<p>Sometimes, tagging domains one-by-one just isn't enough. Welcome to metasmoke: now with mass tagging!</p>

<div class="panel panel-default">
  <div class="panel-body">
    <h4>Using this filter...</h4>
    <%= form_tag domain_tags_mass_tagging_path, method: :get, class: 'form-inline' do %>
        <%= text_field_tag :filter, params[:filter], class: 'form-control input-sm', placeholder: 'Literal search, use * as wildcard' %>
        <%= submit_tag 'Filter', class: 'btn btn-primary btn-sm' %>
    <% end %>

    <h4>...gets you these domains:</h4>
  </div>
  <table class="table table-striped">
    <thead>
    <tr>
      <th>Domain</th>
      <th>Occurrences</th>
      <th colspan="3"></th>
    </tr>
    </thead>
    <tbody>
    <% @domains.each do |d| %>
        <tr>
          <td><code><%= d.domain %></code></td>
          <td><%= @counts[d.id] || 0 %></td>
          <td><%= link_to 'Details', spam_domain_path(d) %></td>
          <% if user_signed_in? && current_user.has_role?(:core) %>
              <td><%= link_to 'Edit', edit_spam_domain_path(d) %></td>
          <% end %>
          <% if user_signed_in? && current_user.has_role?(:admin) %>
              <td><%= link_to 'Delete', destroy_spam_domain_path(d), method: :delete, class: 'text-danger',
                                                data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        </tr>
    <% end %>
    </tbody>
  </table>

  <div class="text-center">
    <%= will_paginate @domains, renderer: BootstrapPagination::Rails %>
  </div>
</div>

<% if @taggable %>
  <h4>Tag all the above with this tag:</h4>
  <%= form_tag domain_tags_submit_tagging_path, method: :post, class: 'form-inline' do %>
    <%= hidden_field_tag :filter, params[:filter] %>
    <%= text_field_tag :tag, '', class: 'form-control input-sm', list: 'tag_list' %>
    <datalist id="tag_list">
      <% DomainTag.all.order(name: :asc).each do |t| %>
          <option value="<%= t.name %>"></option>
      <% end %>
    </datalist>
    <%= submit_tag 'Tag!', class: 'btn btn-primary btn-sm' %>
  <% end %>
<% else %>
  <h4 class="text-muted">(Add a filter to mass-tag domains)</h4>
<% end %>

app/views/domain_tags/show.html.erb
<h3>Tag: <%= render 'tag', tag: @tag %></h3>
<% if @counts_summary %>
  <%= @counts_summary[:all] %>
  (<span class="text-success" title="TP" data-toggle="tooltip"><%= @counts_summary[:tp] %></span>,
  <span class="text-danger" title="FP" data-toggle="tooltip"><%= @counts_summary[:fp] %></span>,
  <span class="text-warning" title="NAA" data-toggle="tooltip"><%= @counts_summary[:naa] %></span>)
<% end %>
<% if @tag.description.present? %>
  <p><%= @tag.description %></p>
<% else %>
  <p><em>No description.</em></p>
<% end %>
<% if user_signed_in? && (current_user.has_role?(:core) || current_user.has_role?(:admin)) %>
  <p>
    <% if current_user.has_role?(:core) %>
      <%= link_to 'Edit', edit_domain_tag_path(@tag) %>
    <% end %>
    <% if current_user.has_role?(:admin) %>
      &middot; <%= link_to 'Delete', destroy_domain_tag_path(@tag), method: :delete,
                    data: { confirm: 'Are you sure?' }, class: 'text-danger' %>
    <% end %>
  </p>
  <%= render 'abuse_reports/list', item: @tag %>
<% end %>

<ul class="nav nav-tabs">
  <li class="<%= 'active' if params[:what] == 'domains' || params[:what].nil? %>"><%= link_to 'Domains', domain_tag_path(@tag, what: 'domains') %></li>
  <li class="<%= 'active' if params[:what] == 'posts' %>"><%= link_to 'Posts', domain_tag_path(@tag, what: 'posts') %></li>
</ul>

<% if params[:what] == 'domains' || params[:what].nil? %>
  <table class="table table-striped domains-table">
    <thead>
    <tr>
      <th>Domain</th>
      <th>Other Tags</th>
      <th>Occurrences</th>
      <th colspan="3"></th>
    </tr>
    </thead>
    <tbody>
      <% @domains.each do |d| %>
        <tr>
          <td><code><%= d.domain %></code></td>
          <td>
            <% (d.domain_tags - [@tag]).each do |t| %>
              <%= render 'tag', tag: t %>
            <% end %>
          </td>
          <td>
            <%= @counts[d.id] || 0 %>
            (<span class="text-success" title="TP" data-toggle="tooltip"><%= @counts_per_domain[:tp][d.id] || 0 %></span>,
            <span class="text-danger" title="FP" data-toggle="tooltip"><%= @counts_per_domain[:fp][d.id] || 0 %></span>,
            <span class="text-warning" title="NAA" data-toggle="tooltip"><%= @counts_per_domain[:naa][d.id] || 0 %></span>)
          </td>
          <td><%= link_to 'Details', spam_domain_path(d) %></td>
          <% if user_signed_in? && current_user.has_role?(:core) %>
            <td><%= link_to 'Edit', edit_spam_domain_path(d) %></td>
          <% end %>
          <% if user_signed_in? && current_user.has_role?(:admin) %>
            <td><%= link_to 'Delete', destroy_spam_domain_path(d), method: :delete, class: 'text-danger',
                            data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= will_paginate @domains, renderer: BootstrapPagination::Rails %>
<% elsif params[:what] == 'posts' %>
  <table class="table posts-table">
    <tbody>
      <% @posts.each do |p| %>
        <%= render 'posts/post', post: p, wrap_in_tr: true %>
      <% end %>
    </tbody>
  </table>

  <%= will_paginate @posts, renderer: BootstrapPagination::Rails %>
<% end %>

<% if current_user&.has_role?(:developer) %>
  <div class="panel panel-danger developer-tools searc-developer-tools">
    <div class="panel-heading">
      <h3 class="panel-title">Developer tools</h3>
    </div>
    <div class="panel-body">
      <%= form_tag merge_tags_path, method: :post, class: 'form-inline' do %>
        <%= hidden_field_tag :source_id, @tag.id %>
        <%= label_tag :target_id, 'Merge this tag with:' %>
        <%= select_tag :target_id, options_for_select(DomainTag.all.map { |t| [t.name, t.id, { 'data-subtext' => t.id }] }),
                       class: 'form-control input-sm selectpicker', include_blank: true %>
        <%= submit_tag 'Merge', class: 'btn btn-sm btn-danger' %>
      <% end %>
    </div>
  </div>
<% end %>