config/routes.rb
# frozen_string_literal: true

# routes.rb style guidance:
#
# - Root at the top
# - Unscoped routes next; group them logically
# - Throw everything else in a scope, alphabetically ordered.
# - Within a scope, unscoped routes go _after_ everything else.
# - Unscoped mounts at the bottom.
#
# RubyMine hint: Within the draw block, Ctrl-Shift-Minus followed by Ctrl-= (or cmd, whatever system you're on)
# will collapse everything and then expand the top level again so you just see unscoped routes plus scopes. Makes
# it much easier to see where everything is.
Rails.application.routes.draw do
  # Needs both with and without :as, ref Charcoal-SE/metasmoke#247
  root               to: 'dashboard#new_dash',  as: :dashboard
  root               to: 'dashboard#new_dash'

  resources :dumps

  get    'sites/dash',            to: 'dashboard#site_dash',        as: :site_dash

  get    'search',                to: 'search#index'
  get    'search_fast',           to: 'search#index_fast'
  get    'reasons',               to: 'dashboard#index',            as: :reasons
  get    'flagging',              to: 'flag_settings#dashboard',    as: :flagging

  get    'query-times',           to: 'dashboard#query_times',      as: :query_times
  post   'query-times/reset',     to: 'dashboard#reset_query_time', as: :reset_query_time

  post   'statistics.json',       to: 'statistics#create'
  post   'feedbacks.json',        to: 'feedbacks#create'
  post   'posts.json',            to: 'posts#create'
  post   'deletion_logs.json',    to: 'deletion_logs#create'
  post   'status-update.json',    to: 'status#status_update'

  delete 'feedback/:id/delete',   to: 'feedbacks#delete',           as: :delete_feedback

  devise_for :users, controllers: { sessions: 'custom_sessions', registrations: 'custom_registrations' }
  devise_scope :user do
    get  'users/2fa/login', to: 'custom_sessions#verify_2fa'
    post 'users/2fa/login', to: 'custom_sessions#verify_code'
  end

  scope 'abuse' do
    scope 'contacts' do
      root               to: 'abuse_contacts#index',   as: :abuse_contacts
      post   'new',      to: 'abuse_contacts#create',  as: :create_abuse_contact
      get    ':id',      to: 'abuse_contacts#show',    as: :abuse_contact
      get    ':id/edit', to: 'abuse_contacts#edit',    as: :edit_abuse_contact
      patch  ':id/edit', to: 'abuse_contacts#update',  as: :update_abuse_contact
      delete ':id',      to: 'abuse_contacts#destroy', as: :destroy_abuse_contact
    end

    scope 'statuses' do
      root               to: 'abuse_report_statuses#index',   as: :abuse_statuses
      post   'new',      to: 'abuse_report_statuses#create',  as: :create_abuse_status
      get    ':id',      to: 'abuse_report_statuses#show',    as: :abuse_status
      get    ':id/edit', to: 'abuse_report_statuses#edit',    as: :edit_abuse_status
      patch  ':id/edit', to: 'abuse_report_statuses#update',  as: :update_abuse_status
      delete ':id',      to: 'abuse_report_statuses#destroy', as: :destroy_abuse_status
    end

    scope 'reports' do
      root                   to: 'abuse_reports#index',         as: :abuse_reports
      get    'new',          to: 'abuse_reports#new',           as: :new_abuse_report
      post   'new',          to: 'abuse_reports#create',        as: :create_abuse_report
      get    'shared/:uuid', to: 'abuse_reports#public_link',   as: :shared_abuse_report
      get    ':id',          to: 'abuse_reports#show',          as: :abuse_report
      patch  ':id/edit',     to: 'abuse_reports#update',        as: :update_abuse_report
      post   ':id/status',   to: 'abuse_reports#update_status', as: :update_abuse_report_status
      delete ':id',          to: 'abuse_reports#destroy',       as: :destroy_abuse_report
    end

    scope 'comments' do
      post   'new',        to: 'abuse_comments#create',  as: :create_abuse_comment
      get    ':id',        to: 'abuse_comments#text',    as: :comment_abuse_text
      post   ':id/edit',   to: 'abuse_comments#update',  as: :edit_abuse_comment
      delete ':id/delete', to: 'abuse_comments#destroy', as: :delete_abuse_comment
    end
  end

  scope 'admin' do
    scope 'settings' do
      root                 to: 'site_settings#index',   as: :site_settings
      post   ':name',      to: 'site_settings#update',  as: :update_site_setting
      delete ':id/delete', to: 'site_settings#destroy', as: :destroy_site_setting
    end

    root                           to: 'admin#index'
    get    'invalidated',          to: 'admin#recently_invalidated'
    get    'user_feedback',        to: 'admin#user_feedback',               as: :admin_user_feedback
    get    'api_feedback',         to: 'admin#api_feedback'
    get    'flagged',              to: 'admin#flagged'
    post   'clear_flag',           to: 'admin#clear_flag'
    get    'users',                to: 'admin#users',                       as: :user_data
    get    'permissions',          to: 'admin#permissions',                 as: :admin_permissions
    put    'permissions/update',   to: 'admin#update_permissions'
    delete 'permissions/:user_id', to: 'admin#destroy_user'

    get    'invalidate_tokens',    to: 'authentication#invalidate_tokens'
    post   'invalidate_tokens',    to: 'authentication#send_invalidations'

    get    'new_key',              to: 'api_keys#new',                      as: :admin_new_key
    post   'new_key',              to: 'api_keys#create'
    get    'keys',                 to: 'api_keys#index'
    get    'keys/mine',            to: 'api_keys#mine'
    get    'edit_key/:id',         to: 'api_keys#edit'
    patch  'edit_key/:id',         to: 'api_keys#update'
    get    'owner_edit/:id',       to: 'api_keys#owner_edit'
    patch  'owner_edit/:id',       to: 'api_keys#owner_update'
    delete 'revoke_write',         to: 'api_keys#revoke_write_tokens'
    delete 'owner_revoke',         to: 'api_keys#owner_revoke'
    post   'keys/:id/trust',       to: 'api_keys#update_trust'
  end

  scope 'announcements' do
    root               to: 'announcements#index',  as: :announcements
    post ':id/expire', to: 'announcements#expire', as: :announcements_expire
    get  'new',        to: 'announcements#new'
    post 'new',        to: 'announcements#create'
    post 'enable',     to: 'users#set_announcement_emails'
  end

  scope 'api' do
    root                            to: 'api#api_docs',              as: :api_docs
    get  'filters',                 to: 'api#filter_generator'
    post 'filters',                 to: 'api#calculate_filter'

    get  'filter_fields',           to: 'api#filter_fields'
    get  'stats/last_week',         to: 'api#spam_last_week'
    get  'stats/detailed_ttd',      to: 'api#detailed_ttd'
    get  'smoke_detectors/status',  to: 'api#current_status'
    get  'smoke_detectors',         to: 'api#smoke_detectors'
    get  'posts/urls',              to: 'api#posts_by_url'
    post 'posts/urls',              to: 'api#posts_by_url'
    get  'posts/feedback',          to: 'api#posts_by_feedback'
    get  'posts/undeleted',         to: 'api#undeleted_posts'
    get  'posts/site',              to: 'api#posts_by_site'
    get  'posts/between',           to: 'api#posts_by_daterange'
    get  'posts/search',            to: 'api#search_posts'
    get  'posts/:ids',              to: 'api#posts'
    get  'post/:id/feedback',       to: 'api#post_feedback'
    get  'post/:id/reasons',        to: 'api#post_reasons'
    get  'post/:id/valid_feedback', to: 'api#post_valid_feedback'
    get  'reasons',                 to: 'api#all_reasons'
    get  'reasons/:ids',            to: 'api#reasons'
    get  'reason/:id/posts',        to: 'api#reason_posts'
    get  'blacklist',               to: 'api#blacklisted_websites'
    get  'users',                   to: 'api#users',                 as: :api_users
    get  'users/code_privileged',   to: 'api#users_with_code_privs'
    get  'post/:id/domains',        to: 'api#post_domains',          as: :api_post_domains
    get  'domains/:id/tags',        to: 'api#domain_tags',           as: :api_domain_tags

    post 'w/post/:id/feedback',     to: 'api#create_feedback'
    post 'w/post/report',           to: 'api#report_post'
    post 'w/post/:id/spam_flag',    to: 'api#spam_flag'
    post 'w/post/:id/deleted',      to: 'api#post_deleted'
    post 'w/domains/:id/add_tag',   to: 'api#add_domain_tag',        as: :api_add_domain_tag

    post 'graphql',                 to: 'graphql#execute',           as: :graphql
    get 'graphql',                  to: 'graphql#query',             as: :query_graphql
  end
  mount GraphiQL::Rails::Engine,  at: '/api/graphiql',                 graphql_path: '/api/graphql', query_params: true

  scope 'authentication' do
    get 'status',                to: 'authentication#status', as: :authentication_status
    get 'redirect_target',       to: 'authentication#redirect_target'
    get 'login_redirect_target', to: 'authentication#login_redirect_target'
  end

  scope 'channels' do
    post 'receive_email', to: 'channels#receive_email',     as: :channels_receive_email
    get  'email',         to: 'channels#get_email_address', as: :channels_email
    get  'link',          to: 'channels#show_link',         as: :channels_link
  end

  scope 'comments' do
    post 'new',          to: 'post_comments#create',  as: :create_comment
    get  ':id',          to: 'post_comments#text',    as: :comment_text
    post ':id/edit',     to: 'post_comments#update',  as: :edit_comment
    delete ':id/delete', to: 'post_comments#destroy', as: :delete_comment
  end

  scope 'data' do
    authenticate(:user, ->(user) { user.has_role?(:core) }) do
      mount Blazer::Engine, at: 'sql'
    end
  end

  scope 'dev' do
    post 'update_sites',     to: 'developer#update_sites',          as: :dev_update_sites
    get  'prod_log',         to: 'developer#production_log',        as: :dev_prod_log

app/models/flag_setting.rb
# frozen_string_literal: true

class FlagSetting < ApplicationRecord
  include Websocket

  audited
  validates :name, uniqueness: true

  def self.[](key)
    find_by(name: key).try(:value)
  end
end

app/controllers/flag_settings_controller.rb
# frozen_string_literal: true

class FlagSettingsController < ApplicationController
  protect_from_forgery except: %i[smokey_disable_flagging update_site_settings]
  before_action :set_flag_setting, only: %i[edit update]
  before_action :verify_admin, except: %i[index audits smokey_disable_flagging dashboard by_site]
  before_action :authenticate_user!, except: %i[index audits smokey_disable_flagging dashboard by_site]
  before_action :check_if_smokedetector, only: [:smokey_disable_flagging]

  # GET /flag_settings
  # GET /flag_settings.json
  def index
    @flag_settings = FlagSetting.all
  end

  # GET /flag_settings/new
  def new
    @flag_setting = FlagSetting.new
  end

  # GET /flag_settings/1/edit
  def edit; end

  # POST /flag_settings
  # POST /flag_settings.json
  def create
    @flag_setting = FlagSetting.new(flag_setting_params)

    respond_to do |format|
      if @flag_setting.save
        format.html { redirect_to flag_settings_path, notice: 'Flag setting was successfully created.' }
        format.json { render :show, status: :created, location: @flag_setting }
      else
        format.html { render :new, status: 422 }
        format.json { render json: @flag_setting.errors, status: :unprocessable_entity }
      end
    end
  end

  def audits
    @audits = Audited::Audit.where(auditable_type: 'FlagSetting')
                            .includes(:auditable, :user)
                            .order(Arel.sql('created_at DESC'))
                            .paginate(page: params[:page], per_page: 100)
  end

  # PATCH/PUT /flag_settings/1
  # PATCH/PUT /flag_settings/1.json
  def update
    respond_to do |format|
      if @flag_setting.update(flag_setting_params)

        if %w[min_accuracy min_post_count].include? @flag_setting.name
          # If an accuracy/post count requirement is changed,
          # we want to re-validate all existing FlagConditions
          # and disable them if they aren't in compliance with the
          # new settings
          RevalidateFlagConditionsJob.perform_later
        end

        format.html { redirect_to flag_settings_path, notice: 'Flag setting was successfully updated.' }
        format.json { render :show, status: :ok, location: @flag_setting }
      else
        format.html { render :edit, status: 422 }
        format.json { render json: @flag_setting.errors, status: :unprocessable_entity }
      end
    end
  end

  # Used by SmokeDetector's !!/stopflagging
  def smokey_disable_flagging
    # -1 == System user in metasmoke prod
    Audited::Audit.as_user(User.find(-1)) do
      FlagSetting.find_by(name: 'flagging_enabled').update(value: '0')
    end

    SmokeDetector.send_message_to_charcoal('**Autoflagging disabled** through chat.')

    render plain: 'OK'
  end

  def dashboard
    @recent_count = FlagLog.auto.where('created_at > ?', 1.day.ago).where(success: true).count
  end

  def by_site
    if params[:site].present?
      @site = Site.find params[:site]
      @flags = FlagLog.where(site: @site)
      @posts = Post.includes_for_post_row.where(id: @flags.where.not(post_id: nil).map(&:post_id))
                   .paginate(per_page: 50, page: params[:page])
    end
    @sites = Site.mains.order(site_name: :asc)
  end

  def site_settings
    @sites = Site.mains.order(site_name: :asc)
    @json = JSON.dump(@sites.map do |s|
      [s.id, { flags_enabled: s.flags_enabled,
               max_flags: s.max_flags_per_post,
               auto_disputed_flags_enabled: s.auto_disputed_flags_enabled,
               name: s.site_name, domain: s.site_domain }]
    end.to_h)
  end

  def update_site_settings
    updata = params[:data]
    updata.each do |k, v|
      next unless v['changed'].present? && v['changed'] == true

      params = {}
      params[:flags_enabled] = v['flags_enabled'] unless v['flags_enabled'].nil?
      params[:max_flags_per_post] = v['max_flags'] unless v['max_flags'].nil?
      unless v['auto_disputed_flags_enabled'].nil?
        params[:auto_disputed_flags_enabled] =
          v['auto_disputed_flags_enabled']
      end
      site = Site.find(k)
      puts "Update: #{site} #{params}"
      site.update(params)
    end
    head :no_content
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_flag_setting
    @flag_setting = FlagSetting.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def flag_setting_params
    params.require(:flag_setting).permit(:name, :value)
  end
end

app/helpers/flag_settings_helper.rb
# frozen_string_literal: true

module FlagSettingsHelper
  def flag_settings_plot_lines(start_time, end_time = Time.now)
    setting_ids = FlagSetting.where(name: %w[max_flags min_accuracy]).pluck(:id)

    audits = Audited::Audit.where(auditable_type: 'FlagSetting')
                           .where(action: 'update')
                           .where(auditable_id: setting_ids)
                           .where(created_at: start_time..end_time)

    audits.map do |a|
      changes = a.audited_changes['value']
      { 'width' => '1', value: a.created_at.to_i * 1000, color: 'lightgrey',
        label: { text: "#{FlagSetting.find(a.auditable_id).name.humanize}: #{changes.first} → #{changes.last}" },
        'zIndex' => 10 }
    end
  end
end

app/views/flag_settings/_form.html.erb
<%= form_for(flag_setting) do |f| %>
  <% if flag_setting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(flag_setting.errors.count, 'error') %> prohibited this flag setting from being saved:</h2>

      <ul>
      <% flag_setting.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br/>
    <%= f.text_field :name, class: 'form-control' %>
  </div><br/>

  <div class="field">
    <%= f.label :value %><br/>
    <%= f.text_field :value, class: 'form-control' %>
  </div><br/>

  <div class="actions">
    <%= f.submit 'Save', class: 'btn btn-success' %>
  </div>
<% end %>

app/views/flag_settings/audits.html.erb
<h3><%= title 'Flag Settings Audit' %></h3>

<table class="table">
  <tr>
    <th>User</th>
    <th>Action</th>
    <th>Setting</th>
    <th>Change</th>
    <th>At</th>
  </tr>

  <% @audits.each do |audit| %>
    <tr>
      <td><%= audit.user.try(:username) %></td>
      <td><%= audit.action %></td>
      <td><code><%= audit.auditable.name %></code></td>
      <% value_change = audit.audited_changes['value'] %>
      <td><code><%= value_change.try(:first) %></code><% if value_change.try(:second).present? %>
        → <code><%= value_change.try(:second) %></code>
      <% end %></td>
      <td><span data-livestamp="<%= audit.created_at.to_i %>" title="<%= audit.created_at %>"></span></td>
    </tr>
  <% end %>
</table>

app/views/flag_settings/by_site.html.erb
<h3>
  Autoflagging by Site
  <% if @site.present? %>
    - <%= @site.site_name %>
  <% end %>
</h3>

<%= form_tag :flagging_by_site, method: :get do %>
  <%= label_tag :site, 'Select a site:' %>
  <%= select_tag :site, options_from_collection_for_select(@sites, 'id', 'site_name') %>
  <%= submit_tag 'Apply', class: 'btn btn-xs btn-primary' %>
<% end %>

<% if @site.present? %>
  <p>
    There have been <strong><%= @flags.count %> attempts</strong> to cast flags automatically on <%= @site.site_name %>.<br/>
    <strong><%= @flags.successful.count %></strong> successful and <strong><%= @flags.failed.count %></strong> failed;
    <strong><%= @flags.successful.tp.count %></strong> (<%= ((@flags.successful.tp.count.to_f / @flags.successful.count) * 100).round(2) %>%) TP and
    <strong><%= @flags.successful.fp.count %></strong> (<%= ((@flags.successful.fp.count.to_f / @flags.successful.count) * 100).round(2) %>%) FP.
  </p>

  <h4>Flagged Posts</h4>
  <table class="table posts-table">
    <% @posts.each do |p| %>
      <%= render 'posts/post', post: p %>
    <% end %>
  </table>
<% end %>

app/views/flag_settings/dashboard.html.erb
<% title "Flagging" %>
<div class="row clearfix">
  <div class="col-md-3">
    <% if FlagSetting['flagging_enabled'] == '0' %>
      <div class="module module-red">
        <div class="module-header">
          <h4 class="module-title"><span class="glyphicon glyphicon-flag"></span> system status</h4>
        </div>
        <div class="module-body">
          <p class="status-text">Flagging is disabled.</p>
        </div>
      </div>
    <% else %>
      <% if FlagSetting['dry_run'] == '1' %>
        <div class="module module-amber">
          <div class="module-header">
            <h4 class="module-title"><span class="glyphicon glyphicon-flag"></span> system status</h4>
          </div>
          <div class="module-body">
            <p class="status-text">Enabled, but dry-running.</p>
          </div>
        </div>
      <% else %>
        <div class="module module-green">
          <div class="module-header">
            <h4 class="module-title"><span class="glyphicon glyphicon-flag"></span> system status</h4>
          </div>
          <div class="module-body">
            <p class="status-text">Enabled &amp; flagging.</p>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="col-md-3">
    <% if FlagSetting['registration_enabled'] == '0' %>
      <div class="module module-red">
        <div class="module-header">
          <h4 class="module-title"><span class="glyphicon glyphicon-edit"></span> registration</h4>
        </div>
        <div class="module-body">
          <p class="status-text">Registration is <strong>closed</strong>.</p>
        </div>
      </div>
    <% else %>
      <div class="module module-green">
        <div class="module-header">
          <h4 class="module-title"><span class="glyphicon glyphicon-edit"></span> registration</h4>
        </div>
        <div class="module-body">
          <p class="status-text">Registration is <strong>open</strong>.</p>
        </div>
      </div>
    <% end %>
  </div>
  <div class="col-md-3">
    <div class="module">
      <div class="module-header">
        <h4 class="module-title"><span class="glyphicon glyphicon-stats"></span> last 24 hours</h4>
      </div>
      <div class="module-body">
        <p>
          <%= link_to flag_logs_path do %>
            <strong><%= pluralize @recent_count, 'flag' %></strong> cast
          <% end %>
        </p>
      </div>
    </div>
  </div>
  <div class="col-md-3">
    <div class="module">
      <div class="module-header">
        <h4 class="module-title"><span class="glyphicon glyphicon-user"></span> flagging & you</h4>
      </div>
      <div class="module-body">
        <% if user_signed_in? %>
          <% if current_user.flags_enabled %>
            <%= link_to flag_logs_by_user_path(current_user) do %>
              <p><strong><%= pluralize current_user.flag_logs.where(is_auto: true, success: true).where('created_at > ?', Date.today).count, 'flag' %></strong> used today</p>
            <% end %>
          <% else %>
            <p class="text-muted"><em>Not registered for flagging.</em></p>
          <% end %>
        <% else %>
          <p class="text-muted"><em>Not signed in.</em></p>
        <% end %>
      </div>
    </div>
  </div>
</div>

<h3>Links</h3>
<ul>
  <li><%= link_to "Unflagged logs", unflagged_logs_path %></li>
  <li><%= link_to "System settings", url_for(controller: :flag_settings, action: :index) %></li>
  <li><%= link_to "Your preferences", url_for(controller: :user_site_settings, action: :index) %></li>
  <li><%= link_to "Your conditions", url_for(controller: :flag_conditions, action: :index) %></li>
</ul>

<% if user_signed_in? && current_user.has_role?(:admin) %>
  <h3>Admin</h3>
  <ul>
    <li><%= link_to "All conditions", url_for(controller: :flag_conditions, action: :full_list) %></li>
    <li><%= link_to "Per-site flag limits", url_for(controller: :flag_settings, action: :site_settings) %></li>
    <li><%= link_to "Invalidate API tokens", url_for(controller: :authentication, action: :invalidate_tokens), class: "text-danger" %></li>
  </ul>

  <h5><strong>User views</strong></h5>
  <%= form_tag url_for(controller: :flag_conditions, action: :user_overview), method: 'GET', class: 'form-inline' do %>
    <div class="field">
      <%= select_tag 'user', options_for_select(User.all.map{|u| [u.try(:username), u.id]}),
                     { class: 'form-control selectpicker', 'data-live-search' => true, 'data-actions-box' => true, 'data-dropup-auto' => false} %>
    </div><br/>
    <%= submit_tag 'View', class: 'btn btn-primary' %>
  <% end %>
<% end %>

<h3>Stats</h3>
<%= pluralize(User.where(flags_enabled: true).count, "active participant") %><br/>
<%= pluralize(FlagLog.auto.where(success: true, is_dry_run: false).count, "spam flag") %> total cast in
<%= time_ago_in_words(FlagLog.auto.where(success: true, is_dry_run: false).first.try(:created_at)) rescue nil %><br/>

<%= pie_chart url_for(controller: :graphs, action: :flagging_results), colors: ['red', 'orange', 'green'] %>
<%= line_chart url_for(controller: :graphs, action: :flagging_timeline), colors: ['red', 'orange', 'green'],
library: { "xAxis": { "plotLines" => flag_settings_plot_lines(1.month.ago)}} %>

app/views/flag_settings/edit.html.erb
<h3><%= title 'Edit Flag Setting' %></h3>

<%= render 'form', flag_setting: @flag_setting %>

app/views/flag_settings/index.html.erb
<h3><%= title 'Flag Settings' %></h3>

<%= link_to 'Change Log', flag_settings_audits_path %>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Value</th>
      <% if user_signed_in? && current_user.has_role?(:admin) %>
        <th></th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% @flag_settings.each do |flag_setting| %>
      <tr>
        <td><%= flag_setting.name.humanize %> (<code><%= flag_setting.name %></code>)</td>
        <td><%= flag_setting.value %></td>
        <% if user_signed_in? && current_user.has_role?(:admin) %>
          <td><%= link_to 'Edit', edit_flag_setting_path(flag_setting) %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if user_signed_in? && current_user.has_role?(:admin) %>
  <%= link_to 'New Flag Setting', new_flag_setting_path %>
<% end %>

app/views/flag_settings/new.html.erb
<h3><%= title 'New Flag Setting' %></h3>

<%= render 'form', flag_setting: @flag_setting %>

app/views/flag_settings/site_settings.html.erb
<h1>Site Settings</h1>
<p>Contains settings that can be configured per SE site.</p>

<input type="text" class="form-control input-sm site-search" placeholder="Filter (press Enter to apply)" /><br/>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Site</th>
      <th>Flags enabled</th>
      <th>Max flags per post</th>
      <th>Auto-modflags enabled</th>
    </tr>
  </thead>
  <tbody>
    <% @sites.each do |s| %>
      <tr data-sid="<%= s.id %>">
        <td><%= HTMLEntities.new.decode s.site_name %></td>
        <td><input type="checkbox" name="flags_enabled" <%= 'checked' if s.flags_enabled %> /></td>
        <td><input type="number" class="form-control input-sm" min="0" max="6" value="<%= s.max_flags_per_post %>" /></td>
        <td><input type="checkbox" name="auto_disputed_flags_enabled" <%= 'checked' if s.auto_disputed_flags_enabled %> /></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="panel panel-warning unsaved-changes">
  <div class="panel-body clearfix">
    <p class="text-warning pull-left">
      <strong>You have unsaved changes.</strong> Click the Save button to persist them to the database.
    </p>
    <span class="pull-right">
      <a href="#" class="save-changes btn btn-warning">Save</a>
    </span>
  </div>
</div>

<script>
  window.flagging_settings = <%= raw(@json) %>;
</script>